function [protocol] = initialize_protocol(n)

switch get_global_variables('prf.space')
    case 'volume'
        flds = {
            'roi_file', ...
            'voxel_tal', ...
            'voxel', ...
            'bold_file', ...
            'bold_size', ...
            'bold_dt', ...
            'bold_t', ...
            'bold', ...
            'stim_file', ...
            'stim_funcof', ...
            'stim_dt', ...
            'stim_t', ...
            'stim'
        };
    case 'surface'
        flds = {
            'roi_file', ...
            'vertex', ...
            'bold_file', ...
            'bold_size', ...
            'bold_dt', ...
            'bold_t', ...
            'bold', ...
            'stim_file', ...
            'stim_funcof', ...
            'stim_dt', ...
            'stim_t', ...
            'stim'
        };
end

protocol = initialize_structure(n, flds); 