function [scans] = initialize_scans(n)

switch get_global_variables('prf.space')
    case 'volume'
        flds = {
            'anat_file', ...
            'roi_file', ...
            'voxel_tal', ...
            'voxel', ...
            'bold_file', ...
            'bold_size', ...
            'bold_nvols', ...
            'bold_dt', ...
            'bold_t', ...
            'bold', ...
            'stim_file', ...
            'stim_funcof', ...
            'stim_dt', ...
            'stim_t', ...
            'stim'
            };
    case 'surface'
        flds = {
            'anat_file', ...
            'roi_file', ...
            'vertex', ...
            'bold_file', ...
            'bold_size', ...
            'bold_nvols', ...
            'bold_dt', ...
            'bold_t', ...
            'bold', ...
            'stim_file', ...
            'stim_funcof', ...
            'stim_dt', ...
            'stim_t', ...
            'stim'
            };
end

scans = initialize_structure(n, flds); 